name: CD

on: workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER: ${{ secrets.SERVER }}
    steps:
      - uses: actions/checkout@v3

      - name: Copy files
        run: ssh -i "$SERVER" "$SSH_PRIVATE_KEY"

