name: CD

on: workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Copy files
        run: scp . "$SSH_PRIVATE_KEY":/.

